### ISSUE TITLE
Allow more than two co-chairs in a TC or OP

### ISSUE THREAD

**Issue by JasonKeirstead** [oasis-board-process-committee/TC-Process#19]
It has been brought to my attention by a member that OASIS TCs are only allowed to have two co-chairs

This is because of this rule in https://www.oasis-open.org/policies-guidelines/oasis-committee-operations-process/

"Each committee must have a [Chair](https://www.oasis-open.org/policies-guidelines/oasis-defined-terms-2018-05-22#dChair) or two co-Chairs." and "The responsibilities of the Chair of a committee may be discharged by no more than two co-Chairs."

I do not understand what the history of this decision is, but I do not see any logical reason we should have this limitation. If a committee decides among themselves to have three or more co-chairs to help them share the load, why shouldn't they be allowed to do that?

**Comment by jordan2175** [comment]
I would personally approve allowing TCs to have more than 2 co-chairs. The CTI TC effectively had 8 chairs for the majority of its existence (at one point we had 10). It was very effective and really helped move things forward.

**Comment by jordan2175** [comment]
We talked about this today in the process committee meeting and we agreed we should allow this. We may consider doing an OBCP to give more context to this. 

This may be the only place changes are needed: https://www.oasis-open.org/policies-guidelines/oasis-committee-operations-process/#chairs

**Comment by jordan2175** [comment]
I have some proposed text in section 1.3.3 of the TC process to address this.

**Comment by jordan2175** [comment]
We talked about this today and we generally agree to do this, but we should think about any rules or clarifications we want to add in addition to this.

**Comment by jordan2175** [comment]
This change was approved by the full board.
