### ISSUE TITLE
The "OASIS Committee Operations Process" document should be hyperlinked

### ISSUE THREAD

**Issue by JasonKeirstead** [oasis-board-process-committee/TC-Process#20]
The TC Process (https://www.oasis-open.org/policies-guidelines/tc-process-2017-05-26/) refers to the "OASIS Committee Operations Process", but it is not a hyperlink - forcing the reader to use Google to locate it.

We should hyperlink it.

**Comment by OASIS-OP-Admin** [comment]
Thanks for the catch Jason. I'll get that fixed.

**Comment by OASIS-OP-Admin** [comment]
@JasonKeirstead - I found 5 references to the Committee Process doc. The one referring to chairs was not linked. I added the link so this is fixed. I suspect the reason it was unlinked was that we were trying to avoid overloading the doc with links. In any case, this one certainly should have been and it's done now.
