### ISSUE TITLE
We must publish the OASIS VDP

### ISSUE THREAD

**Issue by JasonKeirstead** [oasis-board-process-committee/TC-Process#3]
The in-progress URLs pointing at these policies are on the mailing list. 

They have been in development since 2018. We desperately need to close this off. Perfect can not be the enemy of the good, these are living documents - lets get them out there and if there are changes to be made we can address that as we go.

**Comment by jordan2175** [comment]
Proposal from Jason, we accept the current version of the document and publish it. This is a policy document that we as OASIS follow.

**Comment by jordan2175** [comment]
These documents were approved and published during the last OASIS Board meeting which was on Wednesday June 14th, 2023.
